### ISSUE TITLE
请问 DedicatedThreadPoolPipeScheduler 调度器有什么优势？

### ISSUE THREAD

**Issue by NMSAzulX** [pinopino/IOCPThreadPool#1]
作者您好，我看到官方使用 PipeScheduler.Inline 作为默认 unix 的调度器，这两个相比有什么异同？是否有性能测试结果？

**Comment by pinopino** [comment]
DedicatedThreadPoolPipeScheduler本质上跟clr线程池没有任何区别，之所以会有这么个东西个人猜测主要还是因为clr的线程池是一个全局的通用的东西，有时候你可能还是会有自己更特化的需求，此时通用的线程池可能就不太合适了；
另外，inline的话其实就是在当前调用栈上继续执行方法而已，少了一些线程上下文切换的开销；不过，由于是当前调用栈执行所以一些耗时的操作可能需要仔细考虑下是否要这样inline执行；

**Comment by NMSAzulX** [comment]
学习了，最近学习一些优化方面的知识，但是线程池这方面是盲点，多谢指导🙏🙏

**Comment by pinopino** [comment]
客气客气。 issue我就关闭了哈 :)

**Comment by NMSAzulX** [comment]
好的，我最近在优化 FreeRedis 兄弟是否有兴趣一起。

**Comment by pinopino** [comment]
刚刚看了下freeredis，大大的一个点赞，先star为敬 :+1: ；
实不相瞒我的crud工作太忙了 并不一定有时间能扑到你们的项目上来，感谢了，以后有机会再一起讨论哦 :)

**Comment by NMSAzulX** [comment]
好的，有不懂的我还得请教你，哈哈。😁

**Comment by pinopino** [comment]
欢迎欢迎 互相学习 互相进步 :)
